name: chat_sockets_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.2
  meta: ^1.7.0
  riverpod: ^2.1.3
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
