name: models_chat
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  json_annotation: ^4.6.0 
  meta: ^1.7.0
  uuid: ^3.0.7

dev_dependencies:
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.0
